# Generated by Django 4.2.7 on 2023-12-20 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='maglumatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Link', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sos_maglumat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mail', models.EmailField(max_length=250, unique=True)),
                ('Instagram', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bannerler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profiliň_ady', models.CharField(max_length=50)),
                ('Имя_профиля', models.CharField(max_length=50)),
                ('Kontakt_maglumaty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bannerler.maglumatlar')),
                ('Sosial_ulgam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bannerler.sos_maglumat')),
            ],
        ),
    ]
