# Generated by Django 4.2.7 on 2023-12-20 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bannerler', '0002_remove_bannerler_kontakt_maglumaty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerler',
            old_name='Profiliň_ady',
            new_name='Banneriň_ady',
        ),
    ]
