# Generated by Django 4.2.7 on 2023-12-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bannerler', '0003_rename_profiliň_ady_bannerler_banneriň_ady'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerler',
            name='Surat',
            field=models.ImageField(default='', upload_to='static/img/bannerler'),
        ),
    ]
