# Generated by Django 4.2.7 on 2023-12-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bannerler', '0006_alter_bannerler_surat'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerler',
            name='Banneriň_ady_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bannerler',
            name='Banneriň_ady_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bannerler',
            name='Banneriň_ady_tk',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
