# Generated by Django 4.2.7 on 2023-12-28 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bannerler', '0007_bannerler_banneriň_ady_en_bannerler_banneriň_ady_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerler',
            name='Banneriň_ady_en',
        ),
        migrations.RemoveField(
            model_name='bannerler',
            name='Banneriň_ady_ru',
        ),
        migrations.RemoveField(
            model_name='bannerler',
            name='Banneriň_ady_tk',
        ),
    ]
