# Generated by Django 4.2.7 on 2023-12-29 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bannerler', '0008_remove_bannerler_banneriň_ady_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerler',
            name='Banneriň_ady',
        ),
        migrations.RemoveField(
            model_name='bannerler',
            name='Instagram',
        ),
        migrations.RemoveField(
            model_name='bannerler',
            name='Mail',
        ),
        migrations.RemoveField(
            model_name='bannerler',
            name='Tel_belgiler',
        ),
    ]
