# Generated by Django 4.2.7 on 2023-12-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tazelikler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tazelikler',
            name='Tazeligiň_maglumaty',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tazelikler',
            name='Tazeligiň_suraty',
            field=models.ImageField(default='', upload_to='static/img/bannerler'),
        ),
    ]
