# Generated by Django 4.2.7 on 2023-12-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tazelikler', '0002_tazelikler_tazeligiň_maglumaty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tazelikler',
            name='Tazeligiň_suraty',
            field=models.ImageField(upload_to='bannerler/'),
        ),
    ]
