# Generated by Django 4.2.7 on 2024-01-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tazelikler', '0003_alter_tazelikler_tazeligiň_suraty'),
    ]

    operations = [
        migrations.AddField(
            model_name='tazelikler',
            name='Tazeligiň_ady_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tazelikler',
            name='Tazeligiň_ady_tk',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tazelikler',
            name='Tazeligiň_maglumaty_ru',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='tazelikler',
            name='Tazeligiň_maglumaty_tk',
            field=models.TextField(default='', null=True),
        ),
    ]
