# Generated by Django 4.2.7 on 2023-12-20 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dolandyrysh_paneli', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dolandyrysh_paneli',
        ),
        migrations.DeleteModel(
            name='maglumatlar',
        ),
        migrations.DeleteModel(
            name='Sos_maglumat',
        ),
    ]
