# Generated by Django 4.2.7 on 2023-12-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiller', '0003_profiller_tel_belgiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiller',
            name='Surat',
            field=models.ImageField(default='', upload_to='static/img/profil'),
        ),
    ]
