# Generated by Django 4.2.7 on 2023-12-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiller', '0005_img_remove_profiller_surat_profiller_suratlar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiller',
            name='Suratlar',
        ),
        migrations.AddField(
            model_name='profiller',
            name='Surat',
            field=models.ImageField(default='', upload_to='static/img/profil'),
        ),
        migrations.DeleteModel(
            name='img',
        ),
    ]
