# Generated by Django 4.2.7 on 2023-12-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiller', '0006_remove_profiller_suratlar_profiller_surat_delete_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiller',
            name='Mail',
            field=models.EmailField(default='', max_length=250),
        ),
    ]
