# Generated by Django 4.2.7 on 2023-12-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiller', '0008_profiller_maglumat_alter_profiller_surat'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarytSurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='profiller/haryt')),
            ],
        ),
        migrations.AlterField(
            model_name='profiller',
            name='Profiliň_ady',
            field=models.CharField(max_length=50, verbose_name='blabla'),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Haryt_suratlar',
            field=models.ManyToManyField(blank=True, related_name='profiller', to='profiller.harytsurat'),
        ),
    ]
