# Generated by Django 4.2.7 on 2023-12-26 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiller', '0010_profileimage_remove_profiller_haryt_suratlar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_af',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_ar',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_ar_dz',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_ast',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_az',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_be',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_bg',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_bn',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_br',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_bs',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_ca',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_ckb',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_cs',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_cy',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_da',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_dsb',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_el',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_en_au',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_en_gb',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_eo',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_es',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_es_ar',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_es_co',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_es_mx',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_es_ni',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_es_ve',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_et',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_eu',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_fa',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_fi',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_fy',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_ga',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_gd',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_gl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_he',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_hi',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_hr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_hsb',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_hu',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_hy',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_ia',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_ig',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_ind',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_io',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_is',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_it',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_ja',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_ka',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_kab',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_kk',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_km',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_kn',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_ko',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_ky',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_lb',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_lt',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_lv',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_mk',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_ml',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_mn',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_mr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_ms',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_my',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_nb',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_ne',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_nl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_nn',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_os',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_pa',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_pl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_pt',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_pt_br',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_ro',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_ru',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_sk',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_sl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_sq',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_sr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_sr_latn',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_sv',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_sw',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_ta',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_te',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_tg',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_th',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_tk',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_tr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_tt',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_udm',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_uk',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_ur',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_uz',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_vi',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_zh_hans',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Maglumat_zh_hant',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='profiller.profiller'),
        ),
    ]
