# Generated by Django 4.2.7 on 2023-12-28 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiller', '0012_remove_profiller_maglumat_af_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiller',
            name='Profiliň_ady_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Profiliň_ady_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Profiliň_ady_tk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Salgy_en',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Salgy_ru',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profiller',
            name='Salgy_tk',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Tel_belgiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tel_belgiler', models.IntegerField()),
                ('Tel_bel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tel_belgiler2', to='profiller.profiller')),
            ],
        ),
    ]
