# Generated by Django 4.2.7 on 2023-12-30 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiller', '0015_alter_profiller_tel_belgiler_delete_phonenumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiller',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 13, 24, 39, 845142, tzinfo=datetime.timezone.utc)),
        ),
    ]
