# Generated by Django 4.2.7 on 2024-01-04 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiller', '0016_profiller_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiller',
            name='Maglumat_en',
        ),
        migrations.RemoveField(
            model_name='profiller',
            name='Profiliň_ady_en',
        ),
        migrations.RemoveField(
            model_name='profiller',
            name='Salgy_en',
        ),
        migrations.AlterField(
            model_name='profiller',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 10, 17, 0, 288913, tzinfo=datetime.timezone.utc)),
        ),
    ]
