# Generated by Django 4.2.7 on 2024-01-04 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiller', '0017_remove_profiller_maglumat_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiller',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 10, 26, 57, 909479, tzinfo=datetime.timezone.utc)),
        ),
    ]
