# Generated by Django 4.2.7 on 2024-01-04 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiller', '0018_alter_profiller_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiller',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 13, 14, 24, 213593, tzinfo=datetime.timezone.utc)),
        ),
    ]
