# Generated by Django 4.2.7 on 2023-12-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='suratlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Suratlar', models.ImageField(default='', upload_to='static/img/bannerler')),
            ],
        ),
    ]
